# Generated by Django 4.1 on 2022-08-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Name")),
                ("last_name", models.CharField(max_length=50, verbose_name="LastName")),
                ("number", models.IntegerField(verbose_name="Number")),
            ],
        ),
    ]
